Changed course card to collapse
Lambda-School-Labs/reach-lms-fe-a pull request #116
Opened 2021-03-25 19:07 UTC by martinezmarina

# What's here (& why)

- (include link(s) to applicable Trello card(s))

# Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete / work-in-progress, PR is for discussion or feedback
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How has this been tested?

- [ ] Tested locally
- [ ] Test suite provides the same results as prior to making changes

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2021-03-26 15:26 UTC, chazkiker2 requested changes
if you add `.env.sample` back into your project and delete the commented-out code, this will be good to go.

2021-03-26 15:26 UTC, chazkiker2 commented on src/components/RestModules/ModuleCard.js
> +// import { Card } from 'antd';
delete commented-out code

2021-03-26 15:26 UTC, chazkiker2 commented on src/components/RestModules/ModuleCard.js
> +      {/* <Card title={module.modulename}>
delete commented-out code

2021-03-26 15:26 UTC, chazkiker2 commented on .env.sample
> -REACT_APP_CLIENT_ID=example
the reason there is a check failing is because you deleted this file... please add this file back into your root folder

2021-03-29 14:58 UTC, sebass482 requested changes
Great changes, some edits needed. 1 check failing.

2021-04-02 02:00 UTC, closed without merging