Testing/test for module table
Lambda-School-Labs/reach-lms-fe-a pull request #117
Opened 2021-03-25 23:07 UTC by BUGBOUNTYchrisg8691

# What's here (& why)

- (include link(s) to applicable Trello card(s))

# Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [x] Incomplete / work-in-progress, PR is for discussion or feedback
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How has this been tested?

- [x] Tested locally
- [ ] Test suite provides the same results as prior to making changes

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2021-03-26 15:33 UTC, chazkiker2 requested changes
looks good for the most part, just a couple of changes left in comment. 

also, it looks like you failed one of the checks. Did you by chance get rid of `.env.sample` at some point?? if so, add that file back in to pass the failing check

2021-03-26 15:33 UTC, chazkiker2 commented on src/components/RestCourses/CourseCard.js
> +// import { Card } from 'antd';
delete commented-out code

2021-03-26 15:33 UTC, chazkiker2 commented on src/components/RestCourses/CourseCard.js
> +    <Collapse accordian className="course-card">
accordion time baby

2021-03-26 15:33 UTC, chazkiker2 commented on src/components/RestModules/EditModuleForm.js
> +            {errors.modulecontent ? `${errors.modulecontent}` : ''}
could replace with `{errors.modulecontent ?? ""}`

2021-03-26 15:33 UTC, chazkiker2 commented on src/components/RestModules/ModuleCard.js
> +        <h3>Description: {module.moduledescription}</h3> */}
delete commented out code

2021-03-26 15:33 UTC, chazkiker2 commented on src/components/RestModules/ModuleCard.js
> +      {/* </Card> */}
delete commented out code

2021-03-26 15:33 UTC, chazkiker2 commented on src/components/RestModules/ModuleCard.js
> +      {props.children}
and if this component now ONLY renders `{props.children}` in a `<React.Fragment />` then it should ~~probably~~ definitely not be a component anymore. just taking up space for no reason

2021-03-26 15:33 UTC, chazkiker2 commented on src/components/RestModules/ModulesTable.js
> +                  console.log('edit module', record._links.self.href);
remove `console.log`

2021-03-26 15:33 UTC, chazkiker2 commented on src/components/RestModules/ModulesTable.js
> +                  console.log('delete module', record._links.self.href);
remove `console.log`

2021-03-27 05:25 UTC, chazkiker2 commented
looks like the only change you made was changing that "accordion" prop... Can you add `.env.sample` back into your project & delete commented-out code??

2021-03-29 15:07 UTC, sebass482 reviewed
Looks good Chris. There is a check failing and Chaz pointed out some stuff so I think there are more commits for this branch? Lmk

2021-03-30 00:48 UTC, closed without merging